#' @name msigdb_immunologic_signatures
#' @title Immunologic signatures
#' 
#' @description
#' Gene sets that represent cell states and perturbations within the immune 
#' system. The signatures were generated by manual curation of published studies
#' in human and mouse immunology. For each study, pairwise comparisons of
#' relevant classes were made and genes ranked by mutual information. Gene sets
#' correspond to top or bottom genes (FDR < 0.25 or maximum of 200 genes) for
#' each comparison. This resource is generated as part of the Human Immunology
#' Project Consortium (HIPC; http://www.immuneprofiling.org/).
#' 
#' @usage data(msigdb_immunologic_signatures)
#' @format A \code{list} of \code{character} of length 1910, with one element
#' per module.
#' 
#' @references http://www.broadinstitute.org/gsea/msigdb/collections.jsp
NULL

#' @name emory_blood_transcript_modules
#' @title Blood transcriptome modules
#' 
#' @usage data(emory_blood_transcript_modules)
#' @format A \code{list} of \code{character} of length 346, with one element per
#' module
#' 
#' @references
#'  http://www.immuneprofiling.org/meni/meni-paper/btm-landing.gsp
#'  http://www.nature.com/ni/journal/v15/n2/full/ni.2789.html
NULL

#' @name chaussabel_modules
#' @title Modules from Chaussabel (2008)
#' 
#' @description
#' Repertoire of co-clustering genes.
#' 
#' @usage data(chaussabel_modules)
#' @format A \code{list} of \code{character} of length 260, with one element per
#' module. 
#' 
#' @references
#'  http://www.biir.net/public_wikis/module_annotation/G2_Trial_8_Modules
#'  http://www.nature.com/nri/journal/v14/n4/full/nri3642.html
NULL